# Generated by Django 4.2.9 on 2024-09-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TOKEN', '0003_borrow_copies_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='copies_returned',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='borrow_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='copies_requested',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
